<?xml version="1.0" encoding="utf-8"?><Database Name="Timsh" Class="Database_ClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=Timsh;Integrated Security=True" SettingsObjectName="Timetable_Data.Properties.Settings" SettingsPropertyName="TimshConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Lecture_Hall" Member="Lecture_Halls">
    <Type Name="Lecture_Hall">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Building" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Floor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Room" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Association Name="Lecture_Hall_Subject_Selection" Member="Subject_Selections" ThisKey="Id" OtherKey="Hall_Id" Type="Subject_Selection" />
    </Type>
  </Table>
  <Table Name="dbo.Lecture_Time" Member="Lecture_Times">
    <Type Name="Lecture_Time">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Time" Type="System.String" DbType="Char(9)" CanBeNull="true" />
      <Association Name="Lecture_Time_Selection_Time" Member="Selection_Times" ThisKey="Id" OtherKey="Lecture_Time_Id" Type="Selection_Time" />
    </Type>
  </Table>
  <Table Name="dbo.Lecturer" Member="Lecturers">
    <Type Name="Lecturer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Lecturer_Selection_Lecturer" Member="Selection_Lecturers" ThisKey="Id" OtherKey="Lecturer_Id" Type="Selection_Lecturer" />
    </Type>
  </Table>
  <Table Name="dbo.Selection_Lecturer" Member="Selection_Lecturers">
    <Type Name="Selection_Lecturer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Selection_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lecturer_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Lecturer_Selection_Lecturer" Member="Lecturer" ThisKey="Lecturer_Id" OtherKey="Id" Type="Lecturer" IsForeignKey="true" />
      <Association Name="Subject_Selection_Selection_Lecturer" Member="Subject_Selection" ThisKey="Selection_Id" OtherKey="Id" Type="Subject_Selection" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Selection_Time" Member="Selection_Times">
    <Type Name="Selection_Time">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Selection_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lecture_Time_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Lecture_Time_Selection_Time" Member="Lecture_Time" ThisKey="Lecture_Time_Id" OtherKey="Id" Type="Lecture_Time" IsForeignKey="true" />
      <Association Name="Subject_Selection_Selection_Time" Member="Subject_Selection" ThisKey="Selection_Id" OtherKey="Id" Type="Subject_Selection" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subject" Member="Subjects">
    <Type Name="Subject">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Subject_Subject_Selection" Member="Subject_Selections" ThisKey="Id" OtherKey="Subject_Id" Type="Subject_Selection" />
    </Type>
  </Table>
  <Table Name="dbo.Subject_Selection" Member="Subject_Selections">
    <Type Name="Subject_Selection">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subject_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hall_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Subject_Selection_Selection_Lecturer" Member="Selection_Lecturers" ThisKey="Id" OtherKey="Selection_Id" Type="Selection_Lecturer" />
      <Association Name="Subject_Selection_Selection_Time" Member="Selection_Times" ThisKey="Id" OtherKey="Selection_Id" Type="Selection_Time" />
      <Association Name="Lecture_Hall_Subject_Selection" Member="Lecture_Hall" ThisKey="Hall_Id" OtherKey="Id" Type="Lecture_Hall" IsForeignKey="true" />
      <Association Name="Subject_Subject_Selection" Member="Subject" ThisKey="Subject_Id" OtherKey="Id" Type="Subject" IsForeignKey="true" />
    </Type>
  </Table>
</Database>